name: Self-Hosted Runner Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Say Hello
        run: echo "✅ Running on Self-Hosted Runner: $HOSTNAME"
